### ISSUE TITLE
It's possible to use the Quest Guide as a learning platform for a different environment ?

### ISSUE THREAD

**Issue by barbosm** [puppetlabs/puppet-quest-guide#126]
For instance, I would like to create a specific quest to teach about networking and routing using VyOS (open source router). It would be possible to adapt the lessons for it ? I do not need the automatic quest progression tracking but maybe a way to input specific lines of config and then match that agains the correct response would be great.

**Comment by kjhenner** [comment]
Hi @barbosm 
The quest tracking we use for the learning vm is handled through the [quest tool(]https://github.com/puppetlabs/quest). It hasn't really been tested outside of the Learning VM content, but in theory you can point it to any directory with spec tests and an index.json file similar to the ones in this repository's tests directory. If you get a chance to try it out, I'd love to hear how it goes!
