### ISSUE TITLE
test for conditional statement task 2 incorrect?

### ISSUE THREAD

**Issue by lailoken503** [puppetlabs/puppet-quest-guide#208]
I'm not getting any increments in my tasks completed due to this. From the test file, conditional_statements_spec.rb,

> describe "Task 2:", host: :localhost do
>   it 'Add the sinatra_server parameter to the pasture config file template' do
>     file("#{MODULE_PATH}pasture/templates/pasture_config.yaml.epp")
>       .content
>       **.should match /<%\-\s+\|.*?\$sinatra_server\s+=\s+(['"])webrick\1,/m**  <-- THIS LINE
>     file("#{MODULE_PATH}pasture/templates/pasture_config.yaml.epp")
>       .content
>       .should match /:sinatra_settings:.*?:server:\s+<%=\s+\$sinatra_server\s+%>/m
>     command("puppet epp validate #{MODULE_PATH}pasture/templates/pasture_config.yaml.epp")
>       .exit_status
>       .should be_zero
>   end
> end
> 

the test file appears to expect pasture/templates/pasture_config.yaml.epp to be:

`<%- | $port,
      $default_character,
      $default_message,
      $sinatra_server = 'webrick',
      | -%>
`

when the tutorial instructions says to write the template down as:

`<%- | $port,
      $default_character,
      $default_message,
      $sinatra_server,
| -%>
`

I've inserted the 'webrick' line in order to increment the quest progress counter, and putting it back the way the tutorial says it should be, results in my progress counter getting reduced.

**Comment by kjhenner** [comment]
At least in the current version, I'm not seeing a test for the pasture_config.yaml.epp file that includes webrick:
https://github.com/puppetlabs/puppet-quest-guide/blob/master/tests/conditional_statements_spec.rb#L18

**Comment by lailoken503** [comment]
I guess I'm a bit outdated. I'm using learning vm 15.5, quest quide 1.2.6.

I'm not sure I want to do a git clone at this point in time, I'll just have to accept that I won't get a full count on the progress.  ;)
