### ISSUE TITLE
Links to The Puppet Forge append the address to the VM's IP address

### ISSUE THREAD

**Issue by mcollins123** [puppetlabs/puppet-quest-guide#259]
## The Issue

On the page "The Forge" in the Puppet quest guide all links to The Forge appends The Forge's URL to the IP of the learning VM so in my case "http://192.168.1.21/en_us/quests/forge.puppet.com". This presents me with a 404.

## Affected Browsers

This issue presented itself in both Google Chrome 69.0.3497.100 and Microsoft Edge 42.17134.1.0

## Proposed Solution

Pre-pending the link with https:// makes the browser go to The Forge URL rather than appending it to the VM's IP.

**Comment by greglarkin** [comment]
Fixed by https://github.com/puppetlabs/puppet-quest-guide/pull/260
