### ISSUE TITLE
Unable to import ova file

### ISSUE THREAD

**Issue by kadiveti** [puppetlabs/puppet-quest-guide#301]
I am trying to import ova file.

I am seeing 0x80070057 Error.

I checked few things disk space,Ram,cpu.

Disk has free space around 100 GB.

Ram is 8 GB.

Tried for the whole day. Didn't see much in googling.

Please help on this. I am new to puppet.

Want to learn.

**Comment by greglarkin** [comment]
Hello @kadiveti , apologies for not seeing this issue sooner. Have you solved this issue already? What type and version of virtualization software are you using to import the Learning VM OVA file?
