### ISSUE TITLE
Manifests and Classes typo?

### ISSUE THREAD

**Issue by clanstyles** [puppetlabs/puppet-quest-guide#97]
On Task 2 the paragraph:

If you were going to apply this code to your production infrastructure, you would use the console's node classifier to classify any nodes that needed cowsay installed with the cowsay with your cowsay class. As you're working on a module, however, it's useful to apply a class directly. By convention, these test manifests are kept in an examples directory. (You may also sometimes see these manifests in the tests directory.)

I assume that "If you were going to apply this code to your production infrastructure, you would use the console's node classifier to classify any nodes that needed cowsay installed with the cowsay with your cowsay class."

should read something like 

"If you were going to apply this code to your production infrastructure, you would use the console's node classifier to classify any nodes that needed cowsay installed with your cowsay class."

**Comment by carthik** [comment]
Thanks for reporting this @clanstyles - We use Jira for issue tracking and this one skipped our attention.
